CREATE SCHEMA SENTINEL.GOLD 
CREATE VIEW SENTINEL.GOLD.ThreatEvents as 
SELECT 
    ACTIONGEO_COUNTRYCODE,
    COUNT(*) as Total_Events,
    AVG(GOLDSTEINSCALE) AS Avg_Severity,
    COUNT(CASE WHEN GOLDSTEINSCALE <=-5 THEN 1 END) as Serious_Events
FROM SENTINEL.SILVER.EVENTS
GROUP BY ACTIONGEO_COUNTRYCODE
ORDER BY  COUNT(CASE WHEN GOLDSTEINSCALE <=-5 THEN 1 END) DESC 